### ISSUE TITLE
Here is my proof of spam that I cannot mint! Why not bro!

### ISSUE THREAD

**Issue by UXSciGuy** [juzybits/polymedia-spam#3]
<img width="682" alt="Screenshot 2024-05-04 at 11 02 00 PM" src="https://github.com/juzybits/polymedia-spam/assets/166039671/d27c1f92-a8de-4c0b-8187-163dc1b3c239">

**Comment by UXSciGuy** [comment]
TX: https://explorer.polymedia.app/object/0x3a877546a2cd116735f2e5890fba8a4025e5e3baffd1642a3618948ba2c09594

**Comment by juzybits** [comment]
You didn't register your counter during the 24h following the spam period, so unfortunately you cannot claim it.

**Comment by UXSciGuy** [comment]
Why was that not in the instructions?

**Comment by UXSciGuy** [comment]
<img width="794" alt="Screenshot 2024-05-06 at 3 42 18 PM" src="https://github.com/juzybits/polymedia-spam/assets/166039671/8ae12bc1-65a4-4578-b987-32259565be76">

I see you updated the instructions. Can you send spam to those who were not informed about the 24 period?

**Comment by juzybits** [comment]
This is a disclaimer for extra clarity (because people don't read the docs). The `create -> spam -> register -> claim` lifecycle of counters was explained repeatedly in the docs and on Twitter from the very beginning.
